# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    env: 
      BASE_URL: ${{ secrets.BASE_URL }}

      STANDARD_USER: ${{ secrets.STANDARD_USER }}
      STANDARD_USER_PASSWORD: ${{ secrets.STANDARD_USER_PASSWORD }}

      LOCKED_OUT_USER: ${{ secrets.LOCKED_OUT_USER }}
      LOCKED_OUT_USER_PASSWORD: ${{ secrets.LOCKED_OUT_USER_PASSWORD }}

      PROBLEM_USER: ${{ secrets.PROBLEM_USER }}
      PROBLEM_USER_PASSWORD: ${{ secrets.PROBLEM_USER_PASSWORD }}

      PERFORMANCE_GLITCH_USER: ${{ secrets.PERFORMANCE_GLITCH_USER }}
      PERFORMANCE_GLITCH_USER_PASSWORD: ${{ secrets.PERFORMANCE_GLITCH_USER_PASSWORD }}

      ERROR_USER: ${{ secrets.ERROR_USER }}
      ERROR_USER_PASSWORD: ${{ secrets.ERROR_USER_PASSWORD }}

      VISUAL_USER: ${{ secrets.VISUAL_USER }}
      VISUAL_USER_PASSWORD: ${{ secrets.VISUAL_USER_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: Install Playwright dependencies
      run: npx playwright install-deps
    - name: Install Playwright
      run: npx playwright install chromium --only-shell
    - name: Run tests
      run: npm test
